// file containing all of the constants for the type of the actions

// nutrition
export const GET_NUTRITION_REQUEST = 'GET_NUTRITION_REQUEST'
export const GET_NUTRITION_SUCCESS = 'GET_NUTRITION_SUCCESS'
export const GET_NUTRITION_ERROR = 'GET_NUTRITION_ERROR'

//program
export const GET_SPORT_REQUEST = 'GET_SPORT_REQUEST'
export const GET_SPORT_SUCCESS = 'GET_SPORT_SUCCESS'
export const GET_SPORT_ERROR = 'GET_SPORT_ERROR'

//user
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR'

// JWT
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR'

//generate program
export const GENERATE_PROGRAM_REQUEST = 'GENERATE_PRGORAM_REQUEST'
export const GENERATE_PROGRAM_SUCCESS = 'GENERATE_PRGORAM_SUCCESS'
export const GENERATE_PROGRAM_ERROR = 'GENERATE_PRGORAM_ERROR'
